import React, { useState, useMemo, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAppStore } from '../store';
import { BarChart3, Star, TrendingDown, ArrowLeft, ChevronDown, ScrollText, Users, Share } from 'lucide-react';

export default function StatsPage() {
  const navigate = useNavigate();
  const { matches, players, activeSeriesId } = useAppStore();
  const [viewType, setViewType] = useState('match'); // match, series, overall
  const [selectedMatchId, setSelectedMatchId] = useState(null);
  const [expandedPlayerId, setExpandedPlayerId] = useState(null);

  const toggleExpand = (id) => {
      setExpandedPlayerId(expandedPlayerId === id ? null : id);
  };

  useEffect(() => {
      if (!selectedMatchId && matches.length > 0) {
          setSelectedMatchId(matches[matches.length - 1].id);
      }
  }, [matches, selectedMatchId]);

  const selectedMatch = matches.find(m => m.id === selectedMatchId) || (matches.length > 0 ? matches[matches.length - 1] : null);
  
  const shareStats = async () => {
      let title = "";
      let body = "";

      if (viewType === 'match' && selectedMatch) {
          const mResult = useAppStore.getState().calculateMatchStats(selectedMatch);
          const teamA = selectedMatch.teamNames?.teamA || 'Team A';
          const teamB = selectedMatch.teamNames?.teamB || 'Team B';
          
          const formatP = (p, i) => {
              const name = players.find(pl => pl.id === p.id)?.name || 'Unknown';
              let tName = "Unknown";
              
              const inning0 = selectedMatch.innings[0];
              const inning1 = selectedMatch.innings[1];
              
              if (inning0.battingState?.[p.id]) {
                  tName = inning0.team === 'teamA' ? teamA : teamB;
              } else if (inning0.bowlingState?.[p.id]) {
                  tName = inning0.team === 'teamA' ? teamB : teamA;
              } else if (inning1?.battingState?.[p.id]) {
                  tName = inning1.team === 'teamA' ? teamA : teamB;
              } else if (inning1?.bowlingState?.[p.id]) {
                  tName = inning1.team === 'teamA' ? teamB : teamA;
              }
              
              return `${i+1}. ${name.toUpperCase()} (${tName})\n` +
                     `   📊 ${p.totalPoints} pts [${p.runsScored}R, ${p.wicketsTaken}W, ${p.fieldingPoints}F]`;
          };

          title = `Match Performance`;
          body = `🏏 *HARIDARSHAN MATCH STATS* 🏏\n` +
                 `🏟️ ${teamA} vs ${teamB}\n\n` +
                 `🏅 *TOP 5 PERFORMERS*:\n` +
                 mResult.mvp.map((p, i) => formatP(p, i)).join('\n') + 
                 `\n\n📉 *BOTTOM 5 PERFORMERS*:\n` +
                 mResult.worst.map((p, i) => formatP(p, i)).join('\n') +
                 `\n\nGenerated by Haridarshan 🚀`;
      } else {
          title = viewType === 'series' ? 'Series Leaderboard' : 'Career Ranking';
          body = `🏏 *HARIDARSHAN ${viewType.toUpperCase()} TOP 5* 🏏\n\n` +
                 aggregatedStats.slice(0, 5).map((p, i) => `${i+1}. ${p.name.toUpperCase()}\n   📊 ${p.points} pts [${p.runs}R, ${p.wickets}W, ${p.matches}M]`).join('\n') +
                 `\n\nGenerated by Haridarshan 🚀`;
      }

      if (navigator.share) {
          try {
              await navigator.share({ title, text: body });
          } catch (e) {}
      } else {
          await navigator.clipboard.writeText(body);
          alert('Copied to clipboard!');
      }
  };

  const formatMatchLabel = (m) => {
    const teamA = m.teamNames?.teamA || 'Team A';
    const teamB = m.teamNames?.teamB || 'Team B';
    const d = new Date(m.startTime);
    const dateStr = `${d.getDate().toString().padStart(2, '0')}/${(d.getMonth()+1).toString().padStart(2, '0')}`;
    return `${teamA} vs ${teamB} - ${dateStr}`;
  };

  const aggregatedStats = useMemo(() => {
     const statsMap = {};
     players.forEach(p => {
         statsMap[p.id] = { 
             id: p.id, name: p.name, 
             runs: 0, ballsFaced: 0, fours: 0, sixes: 0, 
             wickets: 0, ballsBowled: 0, runsGiven: 0, wides: 0, noBalls: 0,
             catches: 0, runouts: 0,
             matches: 0, points: 0 
         };
     });

      const targetMatches = viewType === 'series' 
         ? matches.filter(m => m.seriesId === activeSeriesId && !m.isDiscarded) 
         : matches.filter(m => !m.isDiscarded);

      targetMatches.forEach(m => {
          const matchResult = useAppStore.getState().calculateMatchStats(m);
          const matchPointsMap = matchResult.allPlayerPoints || {};

          Object.entries(matchPointsMap).forEach(([pid, pData]) => {
              if (!statsMap[pid]) {
                  const pObj = players.find(x => x.id === pid);
                  statsMap[pid] = { 
                      id: pid, name: pObj?.name || 'Unknown', 
                      runs: 0, ballsFaced: 0, fours: 0, sixes: 0, 
                      wickets: 0, ballsBowled: 0, runsGiven: 0, wides: 0, noBalls: 0,
                      catches: 0, runouts: 0,
                      matches: 0, points: 0 
                  };
              }
              statsMap[pid].runs += (pData.runsScored || 0);
              statsMap[pid].ballsFaced += (pData.ballsFaced || 0);
              statsMap[pid].fours += (pData.fours || 0);
              statsMap[pid].sixes += (pData.sixes || 0);
              statsMap[pid].wickets += (pData.wicketsTaken || 0);
              statsMap[pid].ballsBowled += (pData.ballsBowled || 0);
              statsMap[pid].runsGiven += (pData.runsGiven || 0);
              statsMap[pid].wides += (pData.wides || 0);
              statsMap[pid].noBalls += (pData.noBalls || 0);
              statsMap[pid].catches += (pData.catches || 0);
              statsMap[pid].runouts += (pData.runouts || 0);
              statsMap[pid].points += (pData.totalPoints || 0);
              statsMap[pid].matches += 1;
          });
      });

     return Object.values(statsMap)
        .filter(s => s.matches > 0)
        .sort((a, b) => b.points - a.points);
  }, [viewType, matches, players, activeSeriesId]);

  const matchStatsToRender = useMemo(() => {
      if (!selectedMatch) return null;
      try {
          return useAppStore.getState().calculateMatchStats(selectedMatch);
      } catch (e) {
          console.error("Match stats calc error:", e);
          return { mvp: [], worst: [] };
      }
  }, [selectedMatch]);

  const renderMVPList = (list, title, isPositive = true) => {
    if (!list || list.length === 0) return null;
    return (
    <div className="card flex-col gap-3">
        <div className="flex items-center gap-2 mb-1 pb-1" style={{ borderBottom: '1px solid var(--border-color)' }}>
            {isPositive ? <Star size={16} color="#fbbf24" fill="#fbbf24" /> : <TrendingDown size={16} color="var(--danger)" />}
            <h3 style={{ margin: 0, fontSize: '0.85rem', fontWeight: '800', color: 'var(--text-main)' }}>{title}</h3>
        </div>
        <div className="flex-col gap-2">
            {list.map((p, idx) => {
                const playerName = p.name || players.find(pl => pl.id === p.id)?.name || 'Unknown';
                let tLabel = "";
                if (viewType === 'match' && selectedMatch) {
                    const inning0 = selectedMatch.innings[0];
                    const inning1 = selectedMatch.innings[1];
                    const { teamA, teamB } = selectedMatch.teamNames;
                    
                    if (inning0.battingState?.[p.id]) {
                        tLabel = inning0.team === 'teamA' ? teamA : teamB;
                    } else if (inning0.bowlingState?.[p.id]) {
                        tLabel = inning0.team === 'teamA' ? teamB : teamA;
                    } else if (inning1?.battingState?.[p.id]) {
                        tLabel = inning1.team === 'teamA' ? teamA : teamB;
                    } else if (inning1?.bowlingState?.[p.id]) {
                        tLabel = inning1.team === 'teamA' ? teamB : teamA;
                    }
                }

                return (
                    <div key={p.id} className="flex-col p-3" style={{ background: 'var(--surface-muted)', borderRadius: '12px' }}>
                        <div className="flex justify-between items-center mb-2">
                            <div className="flex items-center gap-3">
                                <span style={{ fontSize: '0.7rem', fontWeight: '900', color: 'var(--text-muted)', width: '15px' }}>{idx + 1}</span>
                                <div className="flex-col">
                                    <span style={{ fontSize: '0.85rem', fontWeight: '800', color: 'var(--text-main)' }}>
                                        {playerName} {tLabel && <span style={{fontSize: '0.65rem', opacity: 0.6}}>({tLabel})</span>}
                                    </span>
                                </div>
                            </div>
                            <div className="flex items-center gap-2">
                                <span style={{ fontSize: '0.9rem', fontWeight: '900', color: isPositive ? 'var(--secondary)' : 'var(--danger)' }}>{p.points || p.totalPoints}</span>
                                <span style={{ fontSize: '0.6rem', fontWeight: '700', color: 'var(--text-muted)' }}>PTS</span>
                            </div>
                        </div>

                        {/* Granular Stats for Match View */}
                        <div className="flex flex-wrap gap-x-4 gap-y-1 opacity-80" style={{ borderTop: '1px solid rgba(255,255,255,0.05)', paddingTop: '6px' }}>
                             {(p.runsScored > 0 || p.ballsFaced > 0) && (
                                <div className="flex items-center gap-1" style={{ fontSize: '0.65rem', fontWeight: '700' }}>
                                    <span>🏏 {p.runsScored}({p.ballsFaced})</span>
                                    {p.fours > 0 && <span style={{color: 'var(--primary)'}}>4sx{p.fours}</span>}
                                    {p.sixes > 0 && <span style={{color: 'var(--primary)'}}>6sx{p.sixes}</span>}
                                </div>
                             )}
                             {p.ballsBowled > 0 && (
                                <div className="flex items-center gap-1" style={{ fontSize: '0.65rem', fontWeight: '700' }}>
                                    <span>🥎 {p.wicketsTaken}/{p.runsGiven}</span>
                                    <span>({p.ballsBowled}b)</span>
                                    {(p.wides > 0 || p.noBalls > 0) && <span style={{color: 'var(--danger)'}}>{p.wides+p.noBalls}ex</span>}
                                </div>
                             )}
                             {(p.catches > 0 || p.runouts > 0) && (
                                <div className="flex items-center gap-1" style={{ fontSize: '0.65rem', fontWeight: '700' }}>
                                    <span>🧤 {p.catches > 0 && `Cx${p.catches}`} {p.runouts > 0 && `ROx${p.runouts}`}</span>
                                </div>
                             )}
                        </div>
                    </div>
                );
            })}
        </div>
    </div>
    );
  };

  return (
    <div className="flex-col" style={{ minHeight: '100vh', paddingBottom: '120px', background: 'var(--background)' }}>
      <header className="header-sticky glass">
         <div className="flex justify-between items-center w-full">
            <div className="flex items-center gap-2">
                <button className="btn btn-surface btn-sm" style={{ padding: '6px' }} onClick={() => navigate('/')}><ArrowLeft size={16} /></button>
                <h2 style={{ fontSize: '1rem', fontWeight: '800' }}>RECORDS & STATS</h2>
            </div>
            <button className="btn btn-primary btn-sm" style={{ padding: '6px 12px', fontSize: '0.7rem', background: '#25D366', borderColor: '#25D366', color: '#fff' }} onClick={shareStats}>
                <Share size={14} /> SHARE
            </button>
         </div>
      </header>

      <div className="container flex-col gap-4">
        
        {/* View Type Toggle */}
        <div className="flex gap-2 p-1" style={{ background: 'var(--surface-muted)', borderRadius: '12px' }}>
            {['match', 'series', 'overall'].map(type => (
                <button key={type} className="flex-1 btn btn-sm" 
                    style={{ background: viewType === type ? 'var(--surface)' : 'transparent', color: viewType === type ? 'var(--text-main)' : 'var(--text-muted)', fontWeight: '800', fontSize: '10.5px' }}
                    onClick={() => setViewType(type)}>{type.toUpperCase()}</button>
            ))}
        </div>

        {viewType === 'match' && matches.length > 0 && (
            <div className="flex-col gap-4">
                <div className="card flex-col gap-3">
                    <label className="label">CHOOSE MATCH RECORD</label>
                    <div style={{ position: 'relative' }}>
                        <select 
                            className="input" 
                            style={{ paddingRight: '40px', fontWeight: '800', appearance: 'none', background: 'var(--surface-muted)' }}
                            value={selectedMatchId || ''}
                            onChange={(e) => setSelectedMatchId(e.target.value)}
                        >
                            {matches.map(m => (
                                <option key={m.id} value={m.id} style={{ color: 'black' }}>{formatMatchLabel(m)}</option>
                            ))}
                        </select>
                        <ChevronDown size={18} style={{ position: 'absolute', right: '12px', top: '50%', transform: 'translateY(-50%)', pointerEvents: 'none', color: 'var(--text-muted)' }} />
                    </div>

                    <button className="btn btn-primary w-full p-4" onClick={() => navigate(`/scorecard/${selectedMatch?.id}`)} style={{ borderRadius: '12px', marginTop: '4px' }}>
                        <ScrollText size={18} /> VIEW FULL SCOREBOARD
                    </button>
                </div>

                 {matchStatsToRender && (
                    <>
                        {renderMVPList(matchStatsToRender.mvp, 'MATCH TOP 5', true)}
                        {renderMVPList(matchStatsToRender.worst, 'MATCH BOTTOM 5', false)}
                    </>
                )}
            </div>
        )}

        {viewType === 'match' && matches.length === 0 && (
            <div className="card text-center py-20 opacity-50" style={{ borderStyle: 'dashed' }}>
                <ScrollText size={32} style={{ margin: '0 auto 12px' }} />
                <p style={{ fontWeight: '800', fontSize: '0.8rem' }}>NO MATCHES COMPLETED</p>
            </div>
        )}

        {(viewType === 'series' || viewType === 'overall') && (
            <div className="flex-col gap-4">
                <div className="flex items-center gap-2 px-2">
                    <Users size={16} color="var(--primary)" />
                    <h3 style={{ fontSize: '0.8rem', fontWeight: '800', textTransform: 'uppercase', color: 'var(--text-muted)' }}>
                        {viewType === 'series' ? 'CURRENT SERIES LEADERS' : 'ALL-TIME CAREER RANKING'}
                    </h3>
                </div>
                
                <div className="flex-col gap-3">
                    {aggregatedStats.length > 0 ? aggregatedStats.map((p, idx) => (
                        <div key={p.id} className="card flex-col p-0 overflow-hidden" 
                             style={{ 
                                background: expandedPlayerId === p.id ? 'var(--surface-muted)' : 'var(--surface)', 
                                border: expandedPlayerId === p.id ? '1px solid var(--primary-glow)' : '1px solid var(--border-color)',
                                transition: 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)'
                             }}>
                            <div className="flex justify-between items-center p-4" onClick={() => toggleExpand(p.id)}>
                                <div className="flex items-center gap-4">
                                    <span style={{ fontSize: '0.75rem', fontWeight: '900', color: 'var(--text-muted)', width: '20px' }}>#{idx + 1}</span>
                                    <div className="flex-col">
                                        <span style={{ fontSize: '0.9rem', fontWeight: '900', color: 'var(--text-main)' }}>{p.name.toUpperCase()}</span>
                                        <span style={{ fontSize: '0.65rem', color: 'var(--text-muted)', fontWeight: '700' }}>{p.matches} MATCHES</span>
                                    </div>
                                </div>
                                <div className="flex items-center gap-4">
                                     <div className="flex-col items-end">
                                        <span style={{ fontSize: '1.2rem', fontWeight: '900', color: 'var(--primary)' }}>{p.points}</span>
                                        <span style={{ fontSize: '0.5rem', fontWeight: '900', color: 'var(--text-muted)', marginTop: '-4px' }}>POINTS</span>
                                     </div>
                                     <ChevronDown size={20} style={{ transition: 'transform 0.3s', transform: expandedPlayerId === p.id ? 'rotate(180deg)' : 'rotate(0)' }} />
                                </div>
                            </div>

                            {expandedPlayerId === p.id && (
                                <div className="flex-col gap-4 p-4 border-t border-white/5 animate-scale-in" style={{ background: 'rgba(0,0,0,0.15)' }}>
                                    <div className="grid grid-cols-2 gap-4">
                                        <div className="flex-col gap-2">
                                            <span style={{ fontSize: '0.6rem', fontWeight: '900', color: 'var(--primary)', borderBottom: '1px solid var(--primary-glow)', paddingBottom: '4px' }}>BATTING</span>
                                            <div className="flex-col gap-1">
                                                <div className="flex justify-between text-xs font-bold"><span>Runs</span> <span>{p.runs}</span></div>
                                                <div className="flex justify-between text-xs font-bold opacity-60"><span>Balls</span> <span>{p.ballsFaced}</span></div>
                                                <div className="flex justify-between text-xs font-bold"><span>6s / 4s</span> <span>{p.sixes} / {p.fours}</span></div>
                                                <div className="flex justify-between text-xs font-black text-primary"><span>SR</span> <span>{p.ballsFaced > 0 ? ((p.runs/p.ballsFaced)*100).toFixed(1) : '0.0'}</span></div>
                                            </div>
                                        </div>
                                        <div className="flex-col gap-2">
                                            <span style={{ fontSize: '0.6rem', fontWeight: '900', color: 'var(--secondary)', borderBottom: '1px solid var(--secondary-glow)', paddingBottom: '4px' }}>BOWLING</span>
                                            <div className="flex-col gap-1">
                                                <div className="flex justify-between text-xs font-bold"><span>Wickets</span> <span style={{color:'var(--secondary)'}}>{p.wickets}</span></div>
                                                <div className="flex justify-between text-xs font-bold opacity-60"><span>Runs Cons.</span> <span>{p.runsGiven}</span></div>
                                                <div className="flex justify-between text-xs font-bold"><span>Balls / Ext.</span> <span>{p.ballsBowled} / {p.wides + p.noBalls}</span></div>
                                                <div className="flex justify-between text-xs font-black text-secondary"><span>Econ</span> <span>{p.ballsBowled > 0 ? ((p.runsGiven/p.ballsBowled)*6).toFixed(2) : '0.00'}</span></div>
                                            </div>
                                        </div>
                                    </div>
                                    <div className="p-3 bg-black/30 rounded-lg flex justify-between items-center">
                                         <span style={{ fontSize: '0.65rem', fontWeight: '800', color: 'var(--text-muted)' }}>FIELDING PROFILE</span>
                                         <span style={{ fontSize: '0.75rem', fontWeight: '900' }}>{p.catches} Catches • {p.runouts} Runouts</span>
                                    </div>
                                    <div className="flex justify-between items-center px-1">
                                         <span style={{ fontSize: '0.6rem', fontWeight: '800', color: 'var(--text-muted)' }}>AVG PTS / MATCH</span>
                                         <span style={{ fontSize: '0.8rem', fontWeight: '900', color: 'var(--primary)' }}>{(p.points / p.matches).toFixed(1)}</span>
                                    </div>
                                </div>
                            )}
                        </div>
                    )) : (
                        <div className="card text-center py-10 opacity-50">
                            <p style={{ fontWeight: '800', fontSize: '0.8rem' }}>NO {viewType.toUpperCase()} DATA FOUND</p>
                        </div>
                    )}
                </div>
            </div>
        )}

      </div>
    </div>
  );
}
